name: wm_doctor
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter_svg: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_gen_runner: ^5.8.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  pinput: ^5.0.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.7.0
  logger: ^2.5.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  fluttertoast: ^8.2.8
  flutter_bloc: ^8.1.6
  jwt_decoder: ^2.0.1
  toastification: ^2.3.0
  easy_localization: ^3.0.7+1
  flutter_rounded_progress_bar: ^0.3.2
  cached_network_image: ^3.4.1
  internet_connection_checker: ^3.0.1
  lottie: ^3.3.1
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/extras/
    - assets/lottie/
    - assets/translations/
    - assets/fonts/



  fonts:
    - family: VelaSans
      fonts:
        - asset: assets/fonts/VelaSans-Regular.ttf
        - asset: assets/fonts/VelaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/VelaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/VelaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/VelaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/VelaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/VelaSans-ExtraBold.ttf
          weight: 800

#  fonts:
#    - family: Vela Sans GX
#      fonts:
##        - asset: fonts/VelaSans-Regular.ttf
##        - asset: fonts/VelaSans-GX.ttf
#        - asset: fonts/VelaSans-Bold.ttf
##        - asset: fonts/VelaSans-ExtraBold.ttf
##        - asset: fonts/VelaSans-Light.ttf
##        - asset: fonts/VelaSans-ExtraLight.ttf
##        - asset: fonts/VelaSans-Medium.ttf
##        - asset: fonts/VelaSans-SemiBold.ttf